version: '3.8'
services:
  reservation-service:
    build: ./ReservasYMesas
    env_file:
      - ../.env
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PORT=3004
    ports:
      - "${RESERVATIONS_AND_TABLES_PORT}:3004"
    depends_on:
      - db
    networks:
      - dev-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - reservations_db_data:/var/lib/mysql
    networks:
      - dev-network

volumes:
  reservations_db_data:

networks:
  dev-network:
    driver: bridge
